function varargout = smoothing_param(varargin)
% M-File changed by desGUIDE 

%	Copyright (c) 2004-2006 by J. Luis
%
%	This program is free software; you can redistribute it and/or modify
%	it under the terms of the GNU General Public License as published by
%	the Free Software Foundation; version 2 of the License.
%
%	This program is distributed in the hope that it will be useful,
%	but WITHOUT ANY WARRANTY; without even the implied warranty of
%	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%	GNU General Public License for more details.
%
%	Contact info: w3.ualg.pt/~jluis/mirone
% --------------------------------------------------------------------

hObject = figure('Tag','figure1','Visible','off');
smoothing_param_LayoutFcn(hObject);
handles = guihandles(hObject);
movegui(hObject,'northeast')

set(handles.edit_SmoothParam,'String',num2str(varargin{1}))
set(handles.edit_Xstart,'String',num2str(varargin{2}(1)))
set(handles.edit_Xstep,'String',num2str(varargin{2}(2)))
set(handles.edit_Xend,'String',num2str(varargin{2}(3)))

handles.smooth = varargin{1};           handles.smooth_orig = varargin{1};
handles.Xstart = varargin{2}(1);        handles.Xstart_orig = varargin{2}(1);
handles.Xstep = varargin{2}(2);         handles.Xstep_orig = varargin{2}(2);
handles.Xend = varargin{2}(3);          handles.Xend_orig = varargin{2}(3);
handles.h_parent_Fig = varargin{3};     handles.h_parent_Axes = varargin{4};
handles.h_dot = varargin{5};			handles.h_lin = varargin{6};

handles.old_cor = get(handles.h_dot, 'Color');
set(handles.h_dot,'Marker','.', 'LineStyle', 'none', 'Color', [1 0 0])

set(hObject,'Visible','on');
guidata(hObject, handles);
if (nargout),	varargout{1} = hObject;		end

% ----------------------------------------------------------------------------
function edit_SmoothParam_Callback(hObject, eventdata, handles)
	xx = get(hObject,'String');
	handles.smooth = str2double(xx);
	guidata(hObject, handles);

% ----------------------------------------------------------------------------
function edit_Xstart_Callback(hObject, eventdata, handles)
	handles.Xstart = str2double(get(hObject,'String'));
	if (handles.Xstart < handles.Xstart_orig)           % x lower than original x_min is not allowed
		handles.Xstart = handles.Xstart_orig;    set(hObject,'String',num2str(handles.Xstart_orig))
	end
	guidata(hObject, handles);

% ----------------------------------------------------------------------------
function edit_Xstep_Callback(hObject, eventdata, handles)
	handles.Xstep = str2double(get(hObject,'String'));
	guidata(hObject, handles);

% ----------------------------------------------------------------------------
function edit_Xend_Callback(hObject, eventdata, handles)
	handles.Xend = str2double(get(hObject,'String'));
	if (handles.Xend > handles.Xend_orig)           % x higher than original x_max is not allowed
		handles.Xend = handles.Xend_orig;    set(hObject,'String',num2str(handles.Xend_orig))
	end
	guidata(hObject, handles);

% ----------------------------------------------------------------------------
function pushbutton_Apply_Callback(hObject, eventdata, handles)
	xx = get(handles.h_dot,'XData');		yy = get(handles.h_dot,'YData');
	new_x = handles.Xstart:handles.Xstep:handles.Xend;
	y = spl_fun('csaps',xx,yy,handles.smooth,new_x);
	set(handles.h_lin,'XData',new_x,'YData',y);

% ----------------------------------------------------------------------------
function pushbutton_ResetOrigin_Callback(hObject, eventdata, handles)
	set(handles.edit_SmoothParam,'String',num2str(handles.smooth_orig))
	set(handles.edit_Xstart,'String',num2str(handles.Xstart_orig))
	set(handles.edit_Xstep,'String',num2str(handles.Xstep_orig))
	set(handles.edit_Xend,'String',num2str(handles.Xend_orig))
	handles.smooth = handles.smooth_orig;		handles.Xstart = handles.Xstart_orig;
	handles.Xstep = handles.Xstep_orig;			handles.Xend = handles.Xend_orig;
	guidata(hObject, handles);

% ----------------------------------------------------------------------------
% --- Executes when user attempts to close figure1.
function figure1_CloseRequestFcn(hObject, eventdata)
	handles = guidata(hObject);
	xx = get(handles.h_lin,'XData');	yy = get(handles.h_lin,'YData');
	set(handles.h_dot, 'XData', xx, 'YData', yy, 'Marker','none', 'Linestyle', '-', 'Color', handles.old_cor)
	delete(handles.figure1);

% ----------------------------------------------------------------------------
% --- Executes on key press over figure1 with no controls selected.
function figure1_KeyPressFcn(hObject, eventdata)
	handles = guidata(hObject);
	xx = get(handles.h_lin,'XData');	yy = get(handles.h_lin,'YData');
	set(handles.h_dot, 'XData', xx, 'YData', yy, 'Marker','none', 'Linestyle', '-', 'Color', handles.old_cor)
	delete(handles.figure1);

% ----------------------------------------------------------------------------
function smoothing_param_LayoutFcn(h1)

set(h1,...
'PaperUnits',get(0,'defaultfigurePaperUnits'),...
'CloseRequestFcn',@figure1_CloseRequestFcn,...
'Color',get(0,'factoryUicontrolBackgroundColor'),...
'KeyPressFcn',@figure1_KeyPressFcn,...
'MenuBar','none',...
'Name','Smoothing Params',...
'NumberTitle','off',...
'Position',[520 722 329 78],...
'RendererMode','manual',...
'Resize','off',...
'Tag','figure1');

uicontrol('Parent',h1,...
'BackgroundColor',[1 1 1],...
'Callback',{@smoothing_param_uicallback,h1,'edit_SmoothParam_Callback'},...
'HorizontalAlignment','left',...
'Position',[10 39 121 21],...
'Style','edit',...
'TooltipString','Enter a Smoothing Parameter between [0 1]',...
'Tag','edit_SmoothParam');

uicontrol('Parent',h1,...
'BackgroundColor',[1 1 1],...
'Callback',{@smoothing_param_uicallback,h1,'edit_Xstart_Callback'},...
'Position',[150 39 51 21],...
'Style','edit',...
'TooltipString','Fitting will start at this x min',...
'Tag','edit_Xstart');

uicontrol('Parent',h1,...
'BackgroundColor',[1 1 1],...
'Callback',{@smoothing_param_uicallback,h1,'edit_Xstep_Callback'},...
'Position',[210 39 51 21],...
'Style','edit',...
'TooltipString','x step for linear interpolation between x_min and x_max',...
'Tag','edit_Xstep');

uicontrol('Parent',h1,...
'BackgroundColor',[1 1 1],...
'Callback',{@smoothing_param_uicallback,h1,'edit_Xend_Callback'},...
'CData',[],...
'Position',[270 39 51 21],...
'Style','edit',...
'TooltipString','Fitting will stop at this x max',...
'Tag','edit_Xend');

uicontrol('Parent',h1,...
'Position',[151 60 51 15],...
'String','X-start',...
'Style','text');

uicontrol('Parent',h1,...
'Position',[210 60 51 15],...
'String','X-step',...
'Style','text');

uicontrol('Parent',h1,...
'Position',[270 60 51 15],...
'String','X-end',...
'Style','text');

uicontrol('Parent',h1,...
'Position',[11 60 119 15],...
'String','Smoothing parameter (p)',...
'Style','text');

uicontrol('Parent',h1,...
'Callback',{@smoothing_param_uicallback,h1,'pushbutton_Apply_Callback'},...
'Position',[256 8 66 21],...
'String','Apply',...
'Tag','pushbutton_Apply');

uicontrol('Parent',h1,...
'Callback',{@smoothing_param_uicallback,h1,'pushbutton_ResetOrigin_Callback'},...
'Position',[10 8 108 23],...
'String','Reset original values',...
'TooltipString','Reset  p, X-start, X-step, X-end to their original values',...
'Tag','pushbutton_ResetOrigin');

function smoothing_param_uicallback(hObject, eventdata, h1, callback_name)
% This function is executed by the callback and than the handles is allways updated.
feval(callback_name,hObject,[],guidata(h1));
