mex -O edison_wrapper_mex.cpp ...
    segm/ms.cpp  segm/msImageProcessor.cpp segm/msSysPrompt.cpp segm/RAList.cpp segm/rlist.cpp ...
    edge/BgEdge.cpp edge/BgImage.cpp edge/BgGlobalFc.cpp edge/BgEdgeList.cpp edge/BgEdgeDetect.cpp ...
	-outdir ..
fprintf(1, 'Done edison_wraper compilation\n');
