function h = waitfig(varargin)
%WAITFIG
%    Member of IMUI
%    Kotaimen.C, 2002/05 - 2002/07, All Rights Reserved

if nargin == 0
	waittext = 'Please wait...';
else
	waittext = varargin{1};
end
handles.fig = figure( ...
		'Name',			'Mirone', ...
		'Units',		'pixel', ...
		'Position',		[200 150 350 50], ...
		'Color',		'w', ...
		'Menubar',		'none', ...
		'NumberTitle',	'off', ...
		'Resize',		'off', ...
		'Visible',		'off', ...
		'Interruptible','off', ...
		'IntegerHandle','off', ...
		'HandleVisibility','off');
handles.txt = uicontrol( ...
		'Parent',		handles.fig, ...
		'Style',		'text', ...
		'Units',		'pixel', ...
		'HorizontalAlignment', 'center', ...
		'Position',		[0 15 350 20], ...
      	'String',		waittext);
movegui(handles.fig, 'center')
set(handles.fig, 'Visible', 'on', 'Color', get(handles.txt, 'BackgroundColor'));
pause(0.01); %pause a little while
h = handles.fig;
