function [hFig,hTxt] = waitfig(varargin)
%WAITFIG

if (nargin == 0),	waittext = 'Please wait...';
else	            waittext = varargin{1};
end
hFig = figure( ...
		'Name',			'Mirone', ...
		'Units',		'pixel', ...
		'Position',		[200 150 350 50], ...
		'Color',		'w', ...
		'Menubar',		'none', ...
		'NumberTitle',	'off', ...
		'Resize',		'off', ...
		'Visible',		'off', ...
		'IntegerHandle','off', ...
		'HandleVisibility','off');
hTxt = uicontrol( ...
		'Parent',		hFig, ...
		'Style',		'text', ...
		'Units',		'pixel', ...
		'HorizontalAlignment', 'center', ...
		'Position',		[0 15 350 20], ...
      	'String',		waittext);
movegui(hFig, 'center')
set(hFig, 'Visible', 'on', 'Color', get(hTxt, 'BackgroundColor'));
pause(0.01); %pause a little while
