function varargout = bg_region_map_tilled(varargin)
% M-File changed by desGUIDE 
% varargin   command line arguments to bg_region_map_tilled (see VARARGIN)

%	Copyright (c) 2004-2006 by J. Luis
%
%	This program is free software; you can redistribute it and/or modify
%	it under the terms of the GNU General Public License as published by
%	the Free Software Foundation; version 2 of the License.
%
%	This program is distributed in the hope that it will be useful,
%	but WITHOUT ANY WARRANTY; without even the implied warranty of
%	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%	GNU General Public License for more details.
%
%	Contact info: w3.ualg.pt/~jluis/mirone
% --------------------------------------------------------------------

	hObject = figure('Tag','figure1','Visible','off');
	bg_region_map_tilled_LayoutFcn(hObject);
	handles = guihandles(hObject);
	movegui(hObject,'center');      % Reposition the window on screen
 
    if (numel(varargin) > 0)
        f_path = varargin{1};
	else
        f_path = [cd filesep 'data' filesep];
    end
    
	handles.f_path = f_path;
	handles.first_WT = 1;       % Flag to signal the first time World Map is used
	handles.h_ll     = [];      % Will contail the handles to the Lower Left pushbutton

	load([f_path 'WorldMapTilled.mat'])
	set_tiles(handles)              % Put the logo tiles in the pusbuttons

	% Choose default command line output for bg_region_map_tilled
	handles.output = hObject;
	guidata(hObject, handles);

	set(hObject,'Visible','on');
	% UIWAIT makes bg_region_map_tilled_export wait for user response (see UIRESUME)
	uiwait(handles.figure1);

	handles = guidata(hObject);
	try
		x_inc = diff(handles.output.X) / (size(handles.output.img,2)-1);
		y_inc = diff(handles.output.Y) / (size(handles.output.img,1)-1);
		handles.output.head = [handles.output.X handles.output.Y 0 255 0 x_inc y_inc];
	catch
		handles.output = [];
	end
	varargout{1} = handles.output;
    delete(handles.figure1);

% --- Executes on button press in pushbutton_45S135E.
function pushbutton_45S135E_Callback(hObject, eventdata, handles)
	out.img = flipdim( imread([handles.f_path '45S135E.jpg']),1 );
	out.X = [135 180];  out.Y = [-90 -45];    out.imgName = [handles.f_path '45S135E.jpg'];
	handles.output = out;   guidata(hObject, handles);  uiresume(handles.figure1);

% ----------------------------------------------------------------------------------------
function push_getImage_CB(hObject, eventdata, handles)
	tileName = get(hObject,'Tooltip');
	if (get(handles.radiobutton_MapTiles,'Val'))
		out.imgName = [handles.f_path tileName '.jpg'];
		out.img = flipdim( imread(out.imgName),1 );
		west = str2double(tileName(numel(tileName)-3:end-1));
		if (tileName(end) == 'W'),	west = -west;		end
		if (get(handles.radio_360,'Val') && west < 0),		west = west + 360;		end
		out.X = [0 45] + west;
		north = str2double(tileName(1:2));
		if (tileName(3) == 'S'),	north = -north;		end
		out.Y = [(north - 45) north];
	else
		out.imgName = [handles.f_path 'etopo2.jpg'];
		out.img = flipdim( imread(out.imgName),1 );
		if (get(handles.radio_180,'Val'))
			out.X = [-180 180];
		else
			out.img = [out.img(:,901:end,:) out.img(:,1:900,:)];	% Not sure if it's right
			out.X = [0 360];
		end
		out.Y = [-90 90];
	end
	handles.output = out;   guidata(hObject, handles);  uiresume(handles.figure1);

% ----------------------------------------------------------------------------------------
function figure1_CloseRequestFcn(hObject, eventdata)
	handles = guidata(hObject);
	if isequal(get(handles.figure1, 'waitstatus'), 'waiting')
		% The GUI is still in UIWAIT, us UIRESUME
		handles.output = [];        % User gave up, return nothing
		guidata(hObject, handles);    uiresume(hObject);
	else
		% The GUI is no longer waiting, just close it
		handles.output = [];        % User gave up, return nothing
		guidata(hObject, handles);    delete(hObject);
	end

% ----------------------------------------------------------------------------------------
function figure1_KeyPressFcn(hObject, eventdata)
	if isequal(get(hObject,'CurrentKey'),'escape')
		handles = guidata(hObject);
		handles.output = [];    % User said no by hitting escape
		guidata(hObject, handles);    uiresume(hObject);
	end

% ----------------------------------------------------------------------------------------
function radiobutton_MapTiles_Callback(hObject, eventdata, handles)
	if (~get(hObject,'Val')),		set(hObject,'Val', 1),		return,		end
	set(handles.radiobutton_WorldMap, 'Value', 0);
	set(gcf,'Name','World Topo Tiles')
	set(handles.h_ll,'Position',[1 1 64 64],'Tooltip','45S180W')
	set_tiles(handles)
	set(handles.h_all,'Visible','on')

% ----------------------------------------------------------------------------------------
function radiobutton_WorldMap_Callback(hObject, eventdata, handles)
	if (~get(hObject,'Val')),		set(hObject,'Val', 1),		return,		end
	set(handles.radiobutton_MapTiles, 'Value', 0);
	set(handles.figure1,'Name','World Topo')
	if (handles.first_WT)           % Don't need to do this all times (if the user plays)
		h_all = findall(handles.figure1,'Style','pushbutton');
		zz = get(h_all,'Position');
		xx = cat(1,zz{:});
		x_min = min(xx(:,1));   x_max = max(xx(:,1));
		y_min = min(xx(:,2));   y_max = max(xx(:,2));
		x_max = x_max + 65;     y_max = y_max + 65;
		handles.h_ll = findobj(h_all,'Tag','pushbutton_45S180W');
		handles.first_WT = 0;   handles.h_all = h_all;
		handles.pushbutonWT_pos = [x_min y_min x_max y_max];
		handles.logo = imread([handles.f_path 'logo_etopo2.jpg']);
		guidata(hObject, handles);
	end
	set(handles.h_all,'Visible','off')
	set(handles.h_ll,'Position',handles.pushbutonWT_pos,'CData',handles.logo,'Visible','on','Tooltip','')

% ----------------------------------------------------------------------------------------
function radio_180_Callback(hObject, eventdata, handles)
	if (~get(hObject,'Val')),		set(hObject,'Val', 1),		return,		end
	set(handles.radio_360, 'Val', 0)

% ----------------------------------------------------------------------------------------
function radio_360_Callback(hObject, eventdata, handles)
	if (~get(hObject,'Val')),		set(hObject,'Val', 1),		return,		end
	set(handles.radio_180, 'Val', 0)

% --------------------------------------------------------------------
function set_tiles(handles)
	load([handles.f_path 'WorldMapTilled.mat'])
	set(handles.pushbutton_90N180W,'CData',i90N180W);   set(handles.pushbutton_90N135W,'CData',i90N135W)
	set(handles.pushbutton_90N090W,'CData',i90N090W);   set(handles.pushbutton_90N045W,'CData',i90N045W)
	set(handles.pushbutton_90N000E,'CData',i90N000E);   set(handles.pushbutton_90N045E,'CData',i90N045E)
	set(handles.pushbutton_90N090E,'CData',i90N090E);   set(handles.pushbutton_90N135E,'CData',i90N135E)
	
	set(handles.pushbutton_45N180W,'CData',i45N180W);   set(handles.pushbutton_45N135W,'CData',i45N135W)
	set(handles.pushbutton_45N090W,'CData',i45N090W);   set(handles.pushbutton_45N045W,'CData',i45N045W)
	set(handles.pushbutton_45N000E,'CData',i45N000E);   set(handles.pushbutton_45N045E,'CData',i45N045E)
	set(handles.pushbutton_45N090E,'CData',i45N090E);   set(handles.pushbutton_45N135E,'CData',i45N135E)
	
	set(handles.pushbutton_00N180W,'CData',i00N180W);   set(handles.pushbutton_00N135W,'CData',i00N135W)
	set(handles.pushbutton_00N090W,'CData',i00N090W);   set(handles.pushbutton_00N045W,'CData',i00N045W)
	set(handles.pushbutton_00N000E,'CData',i00N000E);   set(handles.pushbutton_00N045E,'CData',i00N045E)
	set(handles.pushbutton_00N090E,'CData',i00N090E);   set(handles.pushbutton_00N135E,'CData',i00N135E)
	
	set(handles.pushbutton_45S180W,'CData',i45S180W);   set(handles.pushbutton_45S135W,'CData',i45S135W)
	set(handles.pushbutton_45S090W,'CData',i45S090W);   set(handles.pushbutton_45S045W,'CData',i45S045W)
	set(handles.pushbutton_45S000E,'CData',i45S000E);   set(handles.pushbutton_45S045E,'CData',i45S045E)
	set(handles.pushbutton_45S090E,'CData',i45S090E);   set(handles.pushbutton_45S135E,'CData',i45S135E)


% --- Creates and returns a handle to the GUI figure. 
function bg_region_map_tilled_LayoutFcn(h1)

set(h1,'PaperUnits','centimeters',...
'CloseRequestFcn',@figure1_CloseRequestFcn,...
'Color',get(0,'factoryUicontrolBackgroundColor'),...
'KeyPressFcn',@figure1_KeyPressFcn,...
'MenuBar','none',...
'Name','World Topo Tiles',...
'NumberTitle','off',...
'Position',[520 525 505 280],...
'Resize','off',...
'Tag','figure1');

% uicontrol('Parent',h1,...
% 'Callback',{@bg_region_map_tilled_uicallback,h1,'pushbutton_90N180W_Callback'},...
% 'Position',[1 190 64 64],...
% 'Tooltip','90N180W',...
% 'Tag','pushbutton_90N180W');

uicontrol('Parent',h1,...
'Callback',{@bg_region_map_tilled_uicallback,h1,'push_getImage_CB'},...
'Position',[1 190 64 64],...
'Tooltip','90N180W',...
'Tag','pushbutton_90N180W');

uicontrol('Parent',h1,...
'Callback',{@bg_region_map_tilled_uicallback,h1,'push_getImage_CB'},...
'Position',[64 190 64 64],...
'Tooltip','90N135W',...
'Tag','pushbutton_90N135W');

uicontrol('Parent',h1,...
'Callback',{@bg_region_map_tilled_uicallback,h1,'push_getImage_CB'},...
'Position',[127 190 64 64],...
'Tooltip','90N090W',...
'Tag','pushbutton_90N090W');

uicontrol('Parent',h1,...
'Callback',{@bg_region_map_tilled_uicallback,h1,'push_getImage_CB'},...
'Position',[190 190 64 64],...
'Tooltip','90N045W',...
'Tag','pushbutton_90N045W');

uicontrol('Parent',h1,...
'Callback',{@bg_region_map_tilled_uicallback,h1,'push_getImage_CB'},...
'Position',[253 190 64 64],...
'Tooltip','90N000E',...
'Tag','pushbutton_90N000E');

uicontrol('Parent',h1,...
'Callback',{@bg_region_map_tilled_uicallback,h1,'push_getImage_CB'},...
'Position',[316 190 64 64],...
'Tooltip','90N045E',...
'Tag','pushbutton_90N045E');

uicontrol('Parent',h1,...
'Callback',{@bg_region_map_tilled_uicallback,h1,'push_getImage_CB'},...
'Position',[379 190 64 64],...
'Tooltip','90N090E',...
'Tag','pushbutton_90N090E');

uicontrol('Parent',h1,...
'Callback',{@bg_region_map_tilled_uicallback,h1,'push_getImage_CB'},...
'Position',[442 190 64 64],...
'Tooltip','90N135E',...
'Tag','pushbutton_90N135E');

uicontrol('Parent',h1,...
'Callback',{@bg_region_map_tilled_uicallback,h1,'push_getImage_CB'},...
'Position',[1 127 64 64],...
'Tooltip','45N180W',...
'Tag','pushbutton_45N180W');

uicontrol('Parent',h1,...
'Callback',{@bg_region_map_tilled_uicallback,h1,'push_getImage_CB'},...
'Position',[64 127 64 64],...
'Tooltip','45N135W',...
'Tag','pushbutton_45N135W');

uicontrol('Parent',h1,...
'Callback',{@bg_region_map_tilled_uicallback,h1,'push_getImage_CB'},...
'Position',[127 127 64 64],...
'Tooltip','45N090W',...
'Tag','pushbutton_45N090W');

uicontrol('Parent',h1,...
'Callback',{@bg_region_map_tilled_uicallback,h1,'push_getImage_CB'},...
'Position',[190 127 64 64],...
'Tooltip','45N045W',...
'Tag','pushbutton_45N045W');

uicontrol('Parent',h1,...
'Callback',{@bg_region_map_tilled_uicallback,h1,'push_getImage_CB'},...
'Position',[253 127 64 64],...
'Tooltip','45N000E',...
'Tag','pushbutton_45N000E');

uicontrol('Parent',h1,...
'Callback',{@bg_region_map_tilled_uicallback,h1,'push_getImage_CB'},...
'Position',[316 127 64 64],...
'Tooltip','45N045E',...
'Tag','pushbutton_45N045E');

uicontrol('Parent',h1,...
'Callback',{@bg_region_map_tilled_uicallback,h1,'push_getImage_CB'},...
'Position',[379 127 64 64],...
'Tooltip','45N090E',...
'Tag','pushbutton_45N090E');

uicontrol('Parent',h1,...
'Callback',{@bg_region_map_tilled_uicallback,h1,'push_getImage_CB'},...
'Position',[442 127 64 64],...
'Tooltip','45N135E',...
'Tag','pushbutton_45N135E');

uicontrol('Parent',h1,...
'Callback',{@bg_region_map_tilled_uicallback,h1,'push_getImage_CB'},...
'Position',[1 64 64 64],...
'Tooltip','00N180W',...
'Tag','pushbutton_00N180W');

uicontrol('Parent',h1,...
'Callback',{@bg_region_map_tilled_uicallback,h1,'push_getImage_CB'},...
'Position',[64 64 64 64],...
'Tooltip','00N135W',...
'Tag','pushbutton_00N135W');

uicontrol('Parent',h1,...
'Callback',{@bg_region_map_tilled_uicallback,h1,'push_getImage_CB'},...
'Position',[127 64 64 64],...
'Tooltip','00N090W',...
'Tag','pushbutton_00N090W');

uicontrol('Parent',h1,...
'Callback',{@bg_region_map_tilled_uicallback,h1,'push_getImage_CB'},...
'Position',[190 64 64 64],...
'Tooltip','00N045W',...
'Tag','pushbutton_00N045W');

uicontrol('Parent',h1,...
'Callback',{@bg_region_map_tilled_uicallback,h1,'push_getImage_CB'},...
'Position',[253 64 64 64],...
'Tooltip','00N000E',...
'Tag','pushbutton_00N000E');

uicontrol('Parent',h1,...
'Callback',{@bg_region_map_tilled_uicallback,h1,'push_getImage_CB'},...
'Position',[316 64 64 64],...
'Tooltip','00N045E',...
'Tag','pushbutton_00N045E');

uicontrol('Parent',h1,...
'Callback',{@bg_region_map_tilled_uicallback,h1,'push_getImage_CB'},...
'Position',[379 64 64 64],...
'Tooltip','00N090E',...
'Tag','pushbutton_00N090E');

uicontrol('Parent',h1,...
'Callback',{@bg_region_map_tilled_uicallback,h1,'push_getImage_CB'},...
'Position',[442 64 64 64],...
'Tooltip','00N135E',...
'Tag','pushbutton_00N135E');

uicontrol('Parent',h1,...
'Callback',{@bg_region_map_tilled_uicallback,h1,'push_getImage_CB'},...
'Position',[1 1 64 64],...
'Tooltip','45S180W',...
'Tag','pushbutton_45S180W');

uicontrol('Parent',h1,...
'Callback',{@bg_region_map_tilled_uicallback,h1,'push_getImage_CB'},...
'Position',[64 1 64 64],...
'Tooltip','45S135W',...
'Tag','pushbutton_45S135W');

uicontrol('Parent',h1,...
'Callback',{@bg_region_map_tilled_uicallback,h1,'push_getImage_CB'},...
'Position',[127 1 64 64],...
'Tooltip','45S090W',...
'Tag','pushbutton_45S090W');

uicontrol('Parent',h1,...
'Callback',{@bg_region_map_tilled_uicallback,h1,'push_getImage_CB'},...
'Position',[190 1 64 64],...
'Tooltip','45S045W',...
'Tag','pushbutton_45S045W');

uicontrol('Parent',h1,...
'Callback',{@bg_region_map_tilled_uicallback,h1,'push_getImage_CB'},...
'Position',[253 1 64 64],...
'Tooltip','45S000E',...
'Tag','pushbutton_45S000E');

uicontrol('Parent',h1,...
'Callback',{@bg_region_map_tilled_uicallback,h1,'push_getImage_CB'},...
'Position',[316 1 64 64],...
'Tooltip','45S045E',...
'Tag','pushbutton_45S045E');

uicontrol('Parent',h1,...
'Callback',{@bg_region_map_tilled_uicallback,h1,'push_getImage_CB'},...
'Position',[379 1 64 64],...
'Tooltip','45S090E',...
'Tag','pushbutton_45S090E');

uicontrol('Parent',h1,...
'Callback',{@bg_region_map_tilled_uicallback,h1,'push_getImage_CB'},...
'Position',[442 1 64 64],...
'Tooltip','45S135E',...
'Tag','pushbutton_45S135E');

uicontrol('Parent',h1,...
'Callback',{@bg_region_map_tilled_uicallback,h1,'radiobutton_MapTiles_Callback'},...
'Position',[10 259 105 15],...
'String','World Map Tiles',...
'Style','radiobutton',...
'Value',1,...
'Tag','radiobutton_MapTiles');

uicontrol('Parent',h1,...
'Callback',{@bg_region_map_tilled_uicallback,h1,'radiobutton_WorldMap_Callback'},...
'Position',[128 259 90 15],...
'String','World Map',...
'Style','radiobutton',...
'Tag','radiobutton_WorldMap');

uicontrol('Parent',h1,...
'Callback',{@bg_region_map_tilled_uicallback,h1,'radio_180_Callback'},...
'Position',[340 259 90 15],...
'String','[-180 180]',...
'Style','radiobutton',...
'Value',1,...
'Tooltip','Central meridian at Greenwich',...
'Tag','radio_180');

uicontrol('Parent',h1,...
'Callback',{@bg_region_map_tilled_uicallback,h1,'radio_360_Callback'},...
'Position',[440 259 90 15],...
'String','[0 360]',...
'Style','radiobutton',...
'Tooltip','Central meridian at date line',...
'Tag','radio_360');

function bg_region_map_tilled_uicallback(hObject, eventdata, h1, callback_name)
% This function is executed by the callback and than the handles is allways updated.
feval(callback_name,hObject,[],guidata(h1));
