function varargout = nearneighbor_options(varargin)
% M-File changed by desGUIDE 
% varargin   command line arguments to nearneighbor_options (see VARARGIN)

%	Copyright (c) 2004-2006 by J. Luis
%
%	This program is free software; you can redistribute it and/or modify
%	it under the terms of the GNU General Public License as published by
%	the Free Software Foundation; version 2 of the License.
%
%	This program is distributed in the hope that it will be useful,
%	but WITHOUT ANY WARRANTY; without even the implied warranty of
%	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%	GNU General Public License for more details.
%
%	Contact info: w3.ualg.pt/~jluis/mirone
% --------------------------------------------------------------------
 
hObject = figure('Tag','figure1','Visible','off');
handles = guihandles(hObject);
guidata(hObject, handles);
nearneighbor_options_LayoutFcn(hObject,handles);
handles = guihandles(hObject);
 
handles.command = cell(20,1);

% Reposition the window on screen
movegui(hObject,'east')

if ~isempty(varargin)
    old_cmd = varargin{1};
end

if ~isempty(old_cmd)        % Decode old command and initialize corresponding boxes
    [tok,rem] = strtok(varargin{1});
    tmp{1} = tok;         i = 2;
    while (rem)
        [tok,rem] = strtok(rem);
        tmp{i} = tok;     i = i + 1;
    end
    for i=1:length(tmp)
        switch tmp{i}(2)
            case 'E'
                handles.command{5} = [' ' tmp{i}];
                set(handles.edit_EmptyNodes,'String',tmp{i}(3:end))
            case 'L'
                switch tmp{i}(3:end);
                    case '',    val = 1;
                    case 'x',   val = 2;
                    case 'y',   val = 3;
                    case 'xy',  val = 4;
                    case 'g',   val = 5;
                end
                handles.command{7} = [' ' tmp{i}];
                set(handles.popup_BoundaryCondition,'Value',val)
            case 'N'
                handles.command{9} = [' ' tmp{i}];
                set(handles.edit_Nsectrors,'String',tmp{i}(3:end))
            case 'W'
                handles.command{11} = [' ' tmp{i}];
                set(handles.checkbox_FourColumns,'Value',1)
        end
    end
    set(handles.edit_ShowCommand, 'String', [handles.command{5:end}]);
end

handles.output = hObject;
guidata(hObject, handles);

% Make the GUI modal
%set(handles.figure1,'WindowStyle','modal')
set(hObject,'Visible','on');
% UIWAIT makes nearneighbor_options_export wait for user response (see UIRESUME)
uiwait(handles.figure1);

handles = guidata(hObject);
out = nearneighbor_options_OutputFcn(hObject, [], handles);
varargout{1} = out;

% --- Outputs from this function are returned to the command line.
function varargout = nearneighbor_options_OutputFcn(hObject, eventdata, handles)
% varargout  cell array for returning output args (see VARARGOUT);
% Get default command line output from handles structure
varargout{1} = handles.output;
% The figure can be deleted now
delete(handles.figure1);

function edit_EmptyNodes_Callback(hObject, eventdata, handles)
handles.command{5} = [' -E' get(hObject,'String')];
set(handles.edit_ShowCommand, 'String', [handles.command{5:end}]);
guidata(hObject, handles);

function pushbutton_help_E_Callback(hObject, eventdata, handles)
message = {'Set the value assigned to empty nodes [NaN].'};
helpdlg(message,'Help -E option');

function popup_BoundaryCondition_Callback(hObject, eventdata, handles)
val = get(hObject,'Value');     str = get(hObject, 'String');
switch str{val};
    case ''
        handles.command{7} = [''];
    case 'x'
        handles.command{7} = [' -Lx'];
    case 'y'
        handles.command{7} = [' -Ly'];
    case 'xy'
        handles.command{7} = [' -Lxy']; 
    case 'g'
        handles.command{7} = [' -Lg'];
end
set(handles.edit_ShowCommand, 'String', [handles.command{5:end}]);
guidata(hObject, handles);
       
function pushbutton_help_L_Callback(hObject, eventdata, handles)
message = {'Boundary condition flag may be x or y or xy indicating data is periodic'
           'in range of x or y or both set by -R (the grids limits in the previous'
           'window), or flag may be g indicating geographical conditions (x and y'
           'are lon and lat). [Default is no boundary conditions].'};
helpdlg(message,'Help -L option');

function edit_Nsectrors_Callback(hObject, eventdata, handles)
xx = get(hObject,'String');
if str2double(xx) < 1 | isnan(str2double(xx))
    set(hObject,'String','4')
    handles.command{9} = [''];
else
    handles.command{9} = [' -N' num2str(fix(str2double(get(hObject,'String'))))];
    set(hObject,'String',num2str(fix(str2double(get(hObject,'String')))))
end
set(handles.edit_ShowCommand, 'String', [handles.command{5:end}]);
guidata(hObject, handles);

function pushbutton_help_N_Callback(hObject, eventdata, handles)
message = {'The circular area centered on each node is divided into several sectors.'
           'Average values will only be computed if there is at least one value inside'
           'each of the sectors for a given node. Nodes that fail this test are'
           'assigned the value NaN (but see Empty nodes -E). [Default is quadrant'
           'search, i.e., sectors = 4]. Note that only the nearest value per sector'
           'enters into the averaging, not all values inside the circle.'};
helpdlg(message,'Help -N option');

function checkbox_FourColumns_Callback(hObject, eventdata, handles)
tmp = get(hObject,'Value');
if tmp
    handles.command{11} = [' -W'];
else
    handles.command{11} = [''];
end
set(handles.edit_ShowCommand, 'String', [handles.command{5:end}]);
guidata(hObject, handles);

function pushbutton_help_W_Callback(hObject, eventdata, handles)
message = {'Input data have a 4th column containing observation point weights.'
           'These are multiplied with the geometrical weight factor to determine'
           'the actual weights used in the calculations.'};
helpdlg(message,'Help -W option');

function popup_FormatInput_Callback(hObject, eventdata, handles)

function edit_ShowCommand_Callback(hObject, eventdata, handles)

function pushbutton_Cancel_Callback(hObject, eventdata, handles)
handles.output = '';        % User gave up, return nothing
guidata(hObject, handles);
uiresume(handles.figure1);

function pushbutton_OK_Callback(hObject, eventdata, handles)
handles.output = get(handles.edit_ShowCommand, 'String');
guidata(hObject,handles)
uiresume(handles.figure1);

% --- Executes when user attempts to close figure1.
function figure1_CloseRequestFcn(hObject, eventdata, handles)
if isequal(get(handles.figure1, 'waitstatus'), 'waiting')
    % The GUI is still in UIWAIT, us UIRESUME
    handles.output = '';        % User gave up, return nothing
    guidata(hObject, handles);
    uiresume(handles.figure1);
else
    % The GUI is no longer waiting, just close it
    handles.output = '';        % User gave up, return nothing
    guidata(hObject, handles);
    delete(handles.figure1);
end

% --- Executes on key press over figure1 with no controls selected.
function figure1_KeyPressFcn(hObject, eventdata, handles)
% Check for "escape"
if isequal(get(hObject,'CurrentKey'),'escape')
    handles.output = '';    % User said no by hitting escape
    % Update handles structure
    guidata(hObject, handles);
    uiresume(handles.figure1);
end    


% --- Creates and returns a handle to the GUI figure. 
function nearneighbor_options_LayoutFcn(h1,handles);

set(h1,...
'PaperUnits','centimeters',...
'CloseRequestFcn',{@figure1_CloseRequestFcn,handles},...
'Color',get(0,'factoryUicontrolBackgroundColor'),...
'KeyPressFcn',{@figure1_KeyPressFcn,handles},...
'MenuBar','none',...
'Name','nearneighbor_options',...
'NumberTitle','off',...
'Position',[265.768111202607 265.768111202607 238 192],...
'RendererMode','manual',...
'Resize','off',...
'Tag','figure1',...
'UserData',[]);

setappdata(h1, 'GUIDEOptions',struct(...
'active_h', [], ...
'taginfo', struct(...
'figure', 2, ...
'edit', 13, ...
'text', 25, ...
'checkbox', 4, ...
'togglebutton', 2, ...
'popupmenu', 3, ...
'pushbutton', 17), ...
'override', 0, ...
'release', 13, ...
'resize', 'none', ...
'accessibility', 'callback', ...
'mfile', 1, ...
'callbacks', 1, ...
'singleton', 1, ...
'syscolorfig', 1, ...
'lastSavedFile', 'D:\m_gmt\nearneighbor_options.m', ...
'blocking', 0));

h2 = uicontrol('Parent',h1,...
'BackgroundColor',[1 1 1],...
'Callback',{@nearneighbor_options_uicallback,h1,'edit_EmptyNodes_Callback'},...
'HorizontalAlignment','left',...
'Position',[10 167 47 21],...
'String','NaN',...
'Style','edit',...
'Tag','edit_EmptyNodes');

h3 = uicontrol('Parent',h1,...
'HorizontalAlignment','left',...
'Position',[61 169 65 16],...
'String','Empty nodes',...
'Style','text',...
'Tag','text_EmptyNodes');

h4 = uicontrol('Parent',h1,...
'BackgroundColor',[1 1 1],...
'Callback',{@nearneighbor_options_uicallback,h1,'popup_BoundaryCondition_Callback'},...
'HorizontalAlignment','right',...
'Position',[10 143 47 21],...
'String',{  ''; 'x'; 'y'; 'xy'; 'g' },...
'Style','popupmenu',...
'Value',1,...
'Tag','popup_BoundaryCondition');

h5 = uicontrol('Parent',h1,...
'HorizontalAlignment','left',...
'Position',[61 145 95 16],...
'String','Boundary condition',...
'Style','text',...
'Tag','text_BoundaryCondition');

h6 = uicontrol('Parent',h1,...
'BackgroundColor',[1 1 1],...
'Callback',{@nearneighbor_options_uicallback,h1,'edit_Nsectrors_Callback'},...
'HorizontalAlignment','left',...
'Position',[10 118 47 21],...
'String','4',...
'Style','edit',...
'Tag','edit_Nsectrors');

h7 = uicontrol('Parent',h1,...
'Callback',{@nearneighbor_options_uicallback,h1,'checkbox_FourColumns_Callback'},...
'Position',[11 91 95 21],...
'String','4 input columns',...
'Style','checkbox',...
'Tag','checkbox_FourColumns');

h8 = uicontrol('Parent',h1,...
'BackgroundColor',[1 1 1],...
'Callback',{@nearneighbor_options_uicallback,h1,'popup_FormatInput_Callback'},...
'Enable','off',...
'Position',[10 64 91 22],...
'String','-f (inactive)',...
'Style','popupmenu',...
'Value',1,...
'Tag','popup_FormatInput');

h9 = uicontrol('Parent',h1,...
'FontSize',10,...
'FontWeight','bold',...
'HorizontalAlignment','left',...
'Position',[168 169 15 16],...
'String','-E',...
'Style','text',...
'Tag','text10');

h10 = uicontrol('Parent',h1,...
'FontSize',10,...
'FontWeight','bold',...
'HorizontalAlignment','left',...
'Position',[168 145 15 16],...
'String','-L',...
'Style','text',...
'Tag','text13');

h11 = uicontrol('Parent',h1,...
'FontSize',10,...
'FontWeight','bold',...
'HorizontalAlignment','left',...
'Position',[168 92 20 16],...
'String','-W',...
'Style','text',...
'Tag','text14');

h12 = uicontrol('Parent',h1,...
'FontSize',10,...
'FontWeight','bold',...
'HorizontalAlignment','left',...
'Position',[166 64 15 16.9],...
'String','-f',...
'Style','text',...
'Tag','text22');

h13 = uicontrol('Parent',h1,...
'Callback',{@nearneighbor_options_uicallback,h1,'pushbutton_Cancel_Callback'},...
'Position',[93 4 66 23],...
'String','Cancel',...
'Tag','pushbutton_Cancel');

h14 = uicontrol('Parent',h1,...
'Callback',{@nearneighbor_options_uicallback,h1,'pushbutton_OK_Callback'},...
'Position',[167 4 65 23],...
'String','OK',...
'Tag','pushbutton_OK');

h15 = uicontrol('Parent',h1,...
'Callback',{@nearneighbor_options_uicallback,h1,'pushbutton_help_E_Callback'},...
'Position',[200 168 30 18],...
'String','Help',...
'Tag','pushbutton_help_E');

h16 = uicontrol('Parent',h1,...
'Callback',{@nearneighbor_options_uicallback,h1,'pushbutton_help_L_Callback'},...
'Position',[200 144 30 18],...
'String','Help',...
'Tag','pushbutton_help_L');

h17 = uicontrol('Parent',h1,...
'Callback',{@nearneighbor_options_uicallback,h1,'pushbutton_help_N_Callback'},...
'Position',[200 119 30 18],...
'String','Help',...
'Tag','pushbutton_help_N');

h18 = uicontrol('Parent',h1,...
'Callback',{@nearneighbor_options_uicallback,h1,'pushbutton_help_W_Callback'},...
'Position',[199 92 30 18],...
'String','Help',...
'Tag','pushbutton_help_W');

h19 = uicontrol('Parent',h1,...
'HorizontalAlignment','left',...
'Position',[61 121 55 16],...
'String','Nº sectors',...
'Style','text',...
'Tag','text23');

h20 = uicontrol('Parent',h1,...
'FontSize',10,...
'FontWeight','bold',...
'HorizontalAlignment','left',...
'Position',[168 120 15 16],...
'String','-N',...
'Style','text',...
'Tag','text24');

h21 = uicontrol('Parent',h1,...
'BackgroundColor',[1 1 1],...
'Callback',{@nearneighbor_options_uicallback,h1,'edit_ShowCommand_Callback'},...
'HorizontalAlignment','left',...
'Position',[10 33 221 21],...
'Style','edit',...
'Tag','edit_ShowCommand');

function nearneighbor_options_uicallback(hObject, eventdata, h1, callback_name)
% This function is executed by the callback and than the handles is allways updated.
feval(callback_name,hObject,[],guidata(h1));
